#cloud-config

coreos:
  fleet:
    etcd_servers: http://<ip>:4001
    endpoint: http://<ip>:4001
    metadata: role=kubernetes
  units:
    - name: etcd.service
      mask: true
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
  update:
    group: alpha
    reboot-strategy: off
